<a href="https://colab.research.google.com/github/kmendesDev/project_titanic/blob/Data_transformation_Cassio/data_cleaning_titanic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Projeto Titanic

## Introdução

👋🛳️ Olá, seja bem-vindo ao Desafio Titanic Kaggle! Esta é a lendária competição de Machine Learning do Titanic - o melhor e primeiro desafio de ML no Kaggle.

Esse projeto foi desenvolvido em colaboração com os Cientistas de Dados:

:iphone: Developers contacts

Kaio Mendes - [![General badge](https://img.shields.io/badge/LinkedIn-0077B5?style=for-the-badge&logo=linkedin&logoColor=white<SUBJECT>-<STATUS>-<COLOR>.svg)](https://www.linkedin.com/in/kaio-mendes-bba196150)  -  [![General badge](https://img.shields.io/badge/GitHub-100000?style=for-the-badge&logo=github&logoColor=white<SUBJECT>-<STATUS>-<COLOR>.svg)](https://github.com/kmendesDev)

Cassio Viana - [![General badge](https://img.shields.io/badge/LinkedIn-0077B5?style=for-the-badge&logo=linkedin&logoColor=white<SUBJECT>-<STATUS>-<COLOR>.svg)](https://www.linkedin.com/in/cvs1987)  -  [![General badge](https://img.shields.io/badge/GitHub-100000?style=for-the-badge&logo=github&logoColor=white<SUBJECT>-<STATUS>-<COLOR>.svg)](https://github.com/cvs2010)


O objetivo desse projeto é utilizar aprendizado de máquina para criar um modelo que preveja quais passageiros sobreviveram ao naufrágio do Titanic.

O Desafio: O naufrágio do Titanic é um dos naufrágios mais infames da história. Em 15 de abril de 1912, durante sua viagem inaugural, o RMS Titanic, amplamente considerado "inafundável", afundou após colidir com um iceberg. Infelizmente, não havia botes salva-vidas suficientes para todos a bordo, resultando na morte de 1502 dos 2224 passageiros e tripulantes.

Embora tenha havido algum elemento de sorte envolvido na sobrevivência, parece que alguns grupos de pessoas tinham mais probabilidade de sobreviver do que outros.

Neste projeto, iremos desenvolver um modelo preditivo de Machine Learning que responda à pergunta: "que tipo de pessoas tinham mais probabilidade de sobreviver?" usando dados dos passageiros (como nome, idade, gênero, classe socioeconômica, etc).

Quais Dados foram usados?
Dois conjuntos de dados semelhantes que incluem informações dos passageiros, como nome, idade, gênero, classe socioeconômica, etc. Um conjunto de dados é intitulado train.csv e o outro é intitulado test.csv.

O train.csv contém os detalhes de um subconjunto dos passageiros a bordo (exatamente 891) e, o que é mais importante, revelará se eles sobreviveram ou não, também conhecido como "verdade básica". Já o conjunto de dados test.csv contém informações semelhantes, mas não revela a "verdade básica" para cada passageiro. Sua tarefa é prever esses resultados.

Usando os padrões encontrados nos dados do train.csv, prevemos se os 418 passageiros a bordo (encontrados no test.csv) sobreviveram.

Confira a pasta "data" para explorar ainda mais os conjuntos de dados.

https://www.kaggle.com/competitions/titanic/overview/description


##Importação de bibliotecas

In [723]:
import pandas as pd # Para manusear dados tabulares
import seaborn as srn # Para gráficos estatísticos
import statistics as sts # Para cálculos matemáticos
import numpy as np # Para operações numéricas
import seaborn as sns # Para visualização de dados estatísticos
import matplotlib.pyplot as plt # Para criação de gráficos
from sklearn.preprocessing import LabelEncoder # Para codificar colunas

##Importação dos dados

In [724]:
# Baixar arquivos salvos no github
!wget https://github.com/kmendesDev/project_titanic/raw/main/data/train.csv
!wget https://github.com/kmendesDev/project_titanic/raw/main/data/test.csv
dataset_test = pd.read_csv("/content/test.csv")
dataset_train = pd.read_csv("/content/train.csv")

--2023-09-02 13:07:57--  https://github.com/kmendesDev/project_titanic/raw/main/data/train.csv
Resolving github.com (github.com)... 140.82.112.3
Connecting to github.com (github.com)|140.82.112.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/kmendesDev/project_titanic/main/data/train.csv [following]
--2023-09-02 13:07:57--  https://raw.githubusercontent.com/kmendesDev/project_titanic/main/data/train.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 61194 (60K) [text/plain]
Saving to: ‘train.csv.6’

train.csv.6         100%[===================>]  59.76K  --.-KB/s    in 0.001s  

2023-09-02 13:07:57 (46.3 MB/s) - ‘train.csv.6’ saved [61194/61194]

--2023-09-02 13:07:57--  https://github.com/k

In [725]:
dataset_train

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [726]:
dataset_train.tail()

PassengerId  Survived  Pclass                                      Name  \
886          887         0       2                     Montvila, Rev. Juozas   
887          888         1       1              Graham, Miss. Margaret Edith   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
889          890         1       1                     Behr, Mr. Karl Howell   
890          891         0       3                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch      Ticket   Fare Cabin Embarked  
886    male  27.0      0      0      211536  13.00   NaN        S  
887  female  19.0      0      0      112053  30.00   B42        S  
888  female   NaN      1      2  W./C. 6607  23.45   NaN        S  
889    male  26.0      0      0      111369  30.00  C148        C  
890    male  32.0      0      0      370376   7.75   NaN        Q

In [727]:
dataset_train.shape

(891, 12)

In [728]:
dataset_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [729]:
dataset_train.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [730]:
dataset_test

PassengerId  Pclass                                          Name  \
0            892       3                              Kelly, Mr. James   
1            893       3              Wilkes, Mrs. James (Ellen Needs)   
2            894       2                     Myles, Mr. Thomas Francis   
3            895       3                              Wirz, Mr. Albert   
4            896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)   
..           ...     ...                                           ...   
413         1305       3                            Spector, Mr. Woolf   
414         1306       1                  Oliva y Ocana, Dona. Fermina   
415         1307       3                  Saether, Mr. Simon Sivertsen   
416         1308       3                           Ware, Mr. Frederick   
417         1309       3                      Peter, Master. Michael J   

        Sex   Age  SibSp  Parch              Ticket      Fare Cabin Embarked  
0      male  34.5      0      0              330911    7.8292   NaN        Q  
1    female  47.0      1      0              363272    7.0000   NaN        S  
2      male  62.0      0      0              240276    9.6875   NaN        Q  
3      male  27.0      0      0              315154    8.6625   NaN        S  
4    female  22.0      1      1             3101298   12.2875   NaN        S  
..      ...   ...    ...    ...                 ...       ...   ...      ...  
413    male   NaN      0      0           A.5. 3236    8.0500   NaN        S  
414  female  39.0      0      0            PC 17758  108.9000  C105        C  
415    male  38.5      0      0  SOTON/O.Q. 3101262    7.2500   NaN        S  
416    male   NaN      0      0              359309    8.0500   NaN        S  
417    male   NaN      1      1                2668   22.3583   NaN        C  

[418 rows x 11 columns]

In [731]:
dataset_test.tail()

PassengerId  Pclass                          Name     Sex   Age  SibSp  \
413         1305       3            Spector, Mr. Woolf    male   NaN      0   
414         1306       1  Oliva y Ocana, Dona. Fermina  female  39.0      0   
415         1307       3  Saether, Mr. Simon Sivertsen    male  38.5      0   
416         1308       3           Ware, Mr. Frederick    male   NaN      0   
417         1309       3      Peter, Master. Michael J    male   NaN      1   

     Parch              Ticket      Fare Cabin Embarked  
413      0           A.5. 3236    8.0500   NaN        S  
414      0            PC 17758  108.9000  C105        C  
415      0  SOTON/O.Q. 3101262    7.2500   NaN        S  
416      0              359309    8.0500   NaN        S  
417      1                2668   22.3583   NaN        C

In [732]:
dataset_test.shape

(418, 11)

In [733]:
dataset_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  418 non-null    int64  
 1   Pclass       418 non-null    int64  
 2   Name         418 non-null    object 
 3   Sex          418 non-null    object 
 4   Age          332 non-null    float64
 5   SibSp        418 non-null    int64  
 6   Parch        418 non-null    int64  
 7   Ticket       418 non-null    object 
 8   Fare         417 non-null    float64
 9   Cabin        91 non-null     object 
 10  Embarked     418 non-null    object 
dtypes: float64(2), int64(4), object(5)
memory usage: 36.0+ KB


In [734]:
dataset_test.describe()

PassengerId      Pclass         Age       SibSp       Parch        Fare
count   418.000000  418.000000  332.000000  418.000000  418.000000  417.000000
mean   1100.500000    2.265550   30.272590    0.447368    0.392344   35.627188
std     120.810458    0.841838   14.181209    0.896760    0.981429   55.907576
min     892.000000    1.000000    0.170000    0.000000    0.000000    0.000000
25%     996.250000    1.000000   21.000000    0.000000    0.000000    7.895800
50%    1100.500000    3.000000   27.000000    0.000000    0.000000   14.454200
75%    1204.750000    3.000000   39.000000    1.000000    0.000000   31.500000
max    1309.000000    3.000000   76.000000    8.000000    9.000000  512.329200

##Análise exploratória dos dados

### Análise do conjunto de dados de treinamento

In [735]:
#Clonando o DataFrame
training_data = dataset_train
training_data

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [736]:
# Informa a identificação do passageiro na lista
training_data['PassengerId'].describe()

count    891.000000
mean     446.000000
std      257.353842
min        1.000000
25%      223.500000
50%      446.000000
75%      668.500000
max      891.000000
Name: PassengerId, dtype: float64

In [737]:
# Coluna Survived:
# Informa a quantidade de 0 e 1 indicando com 1 os que sobreviveram e com 0 os que não conseguiram.
training_data.groupby(['Survived']).size()

Survived
0    549
1    342
dtype: int64

In [738]:
# Verificando a quantidade de itens na coluna Survived
training_data['Survived'].describe()

count    891.000000
mean       0.383838
std        0.486592
min        0.000000
25%        0.000000
50%        0.000000
75%        1.000000
max        1.000000
Name: Survived, dtype: float64

In [739]:
# Coluna Pclass:
# Informa a classe na qual o passageiro viajava:
training_data.groupby(['Pclass']).size()

Pclass
1    216
2    184
3    491
dtype: int64

In [740]:
# Conferindo a quantidade.
training_data['Pclass'].describe()

count    891.000000
mean       2.308642
std        0.836071
min        1.000000
25%        2.000000
50%        3.000000
75%        3.000000
max        3.000000
Name: Pclass, dtype: float64

In [741]:
# Conferindo a quantidade.
training_data['Name'].describe()

count                         891
unique                        891
top       Braund, Mr. Owen Harris
freq                            1
Name: Name, dtype: object

In [742]:
# Coluna sex:
# Informa a quantidade de homens e mulheres:
training_data['Sex'].value_counts()

male      577
female    314
Name: Sex, dtype: int64

In [743]:
# Conferindo a quantidade.
training_data['Sex'].describe()

count      891
unique       2
top       male
freq       577
Name: Sex, dtype: object

In [744]:
# Coluna Age:
# Verificar a idade dos passageiros:
training_data['Age'].describe()
# A quantidade está inferior à 891. Logo temos problemas com quantitativo nessa coluna

count    714.000000
mean      29.699118
std       14.526497
min        0.420000
25%       20.125000
50%       28.000000
75%       38.000000
max       80.000000
Name: Age, dtype: float64

In [745]:
# Coluna SibSp:
# Informa a quantidade de irmãos e/ou cônjuges à bordo:
training_data['SibSp'].value_counts()

0    608
1    209
2     28
4     18
3     16
8      7
5      5
Name: SibSp, dtype: int64

In [746]:
# Conferindo a quantidade.
training_data['SibSp'].describe()

count    891.000000
mean       0.523008
std        1.102743
min        0.000000
25%        0.000000
50%        0.000000
75%        1.000000
max        8.000000
Name: SibSp, dtype: float64

In [747]:
# Coluna Parch:
# Informa a quantidade de pais e/ou filhos à bordo:
training_data['Parch'].value_counts()

0    678
1    118
2     80
5      5
3      5
4      4
6      1
Name: Parch, dtype: int64

In [748]:
# Conferindo a quantidade.
training_data['Parch'].describe()

count    891.000000
mean       0.381594
std        0.806057
min        0.000000
25%        0.000000
50%        0.000000
75%        0.000000
max        6.000000
Name: Parch, dtype: float64

In [749]:
# Coluna Ticket:
# Informa a numeração do Ticket de cada indivíduo:
training_data['Ticket'].value_counts()

347082      7
CA. 2343    7
1601        7
3101295     6
CA 2144     6
           ..
9234        1
19988       1
2693        1
PC 17612    1
370376      1
Name: Ticket, Length: 681, dtype: int64

In [750]:
# Conferindo a quantidade.
training_data['Ticket'].describe()

count        891
unique       681
top       347082
freq           7
Name: Ticket, dtype: object

In [751]:
# Coluna Fare:
# Informa a tarifa paga:
training_data['Fare'].describe()

count    891.000000
mean      32.204208
std       49.693429
min        0.000000
25%        7.910400
50%       14.454200
75%       31.000000
max      512.329200
Name: Fare, dtype: float64

In [752]:
# Coluna Cabin:
# Informa a cabina que o passageiro ocupava:
training_data['Cabin'].value_counts()
# Verifica-se que a cabine mais recorrente é a B96

B96 B98        4
G6             4
C23 C25 C27    4
C22 C26        3
F33            3
              ..
E34            1
C7             1
C54            1
E36            1
C148           1
Name: Cabin, Length: 147, dtype: int64

In [753]:
# Conferindo a quantidade.
training_data['Cabin'].describe()
# Verifica-se que faltam muitos valores. Temos apenas 204 preenchidos

count         204
unique        147
top       B96 B98
freq            4
Name: Cabin, dtype: object

In [754]:
# Coluna Embarked:
# Informa o porto o qual o passageiro embarcou:
training_data['Embarked'].value_counts()
# O Porto de Southampton (S) é o mais recorrente.

S    644
C    168
Q     77
Name: Embarked, dtype: int64

In [755]:
# Conferindo a quantidade.
training_data['Embarked'].describe()

count     889
unique      3
top         S
freq      644
Name: Embarked, dtype: object

Verificação de valores NaN

In [756]:
training_data.isnull().sum()
# Colunas com valores nulos:
# Age
# Cabin
# Embarked

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

Retirando os valores nulos:

In [757]:
#Substituindo os valores NaN pela média:
training_data['Age'].fillna(int(training_data['Age'].describe()[1]),inplace=True)
int(training_data['Age'].describe()[1])

29

In [758]:
#Verificando a existência de algum valor NaN:
training_data['Age'].isnull().sum()

0

In [759]:
# Coluna Cabin:
training_data['Cabin'].isnull().sum()
#Verifica-se 687 valores nulos, caracterizando mais da metade.

687

In [760]:
# Coluna Embarked:
training_data['Embarked'].isnull().sum()
#Verifica-se 2 valores nulos na coluna Embarked.

2

In [761]:
training_data['Embarked'].fillna('S',inplace=True)

In [762]:
# Verificando se ainda há valores nulos:
training_data['Embarked'].isnull().sum()

0

In [763]:
#Verificando a nova quantidade de dados por variável:
training_data['Embarked'].value_counts()

S    646
C    168
Q     77
Name: Embarked, dtype: int64

Verificando valores duplicados de algumas colunas: Id, Name e Cabin

In [764]:
# Coluna PassengerId
training_data[training_data.duplicated(['PassengerId'],keep=False)]
# Verifica-se que não há valores duplicados

Empty DataFrame
Columns: [PassengerId, Survived, Pclass, Name, Sex, Age, SibSp, Parch, Ticket, Fare, Cabin, Embarked]
Index: []

In [765]:
# Coluna Name
training_data[training_data.duplicated(['Name'],keep=False)]
# Verifica-se que não há valores duplicados

Empty DataFrame
Columns: [PassengerId, Survived, Pclass, Name, Sex, Age, SibSp, Parch, Ticket, Fare, Cabin, Embarked]
Index: []

In [766]:
# Filtra os dados duplicados e não nulos na coluna 'Cabin'
filtered_data_cabin = training_data[training_data['Cabin'].duplicated(keep=False) & training_data['Cabin'].notna()]
# Ordena os dados
filtered_data_cabin = filtered_data_cabin.sort_values(by='Cabin')
# Excluindo o indice
filtered_data_cabin.reset_index(drop=True)
# Exibe os dados
filtered_data_cabin

PassengerId  Survived  Pclass  \
329          330         1       1   
523          524         1       1   
781          782         1       1   
690          691         1       1   
745          746         0       1   
..           ...       ...     ...   
618          619         1       2   
251          252         0       3   
10            11         1       3   
205          206         0       3   
394          395         1       3   

                                                  Name     Sex   Age  SibSp  \
329                       Hippach, Miss. Jean Gertrude  female  16.0      0   
523    Hippach, Mrs. Louis Albert (Ida Sophia Fischer)  female  44.0      0   
781          Dick, Mrs. Albert Adrian (Vera Gillespie)  female  17.0      1   
690                            Dick, Mr. Albert Adrian    male  31.0      1   
745                       Crosby, Capt. Edward Gifford    male  70.0      1   
..                                                 ...     ...   ...    ...   
618                        Becker, Miss. Marion Louise  female   4.0      2   
251         Strom, Mrs. Wilhelm (Elna Matilda Persson)  female  29.0      1   
10                     Sandstrom, Miss. Marguerite Rut  female   4.0      1   
205                         Strom, Miss. Telma Matilda  female   2.0      0   
394  Sandstrom, Mrs. Hjalmar (Agnes Charlotta Bengt...  female  24.0      0   

     Parch     Ticket     Fare Cabin Embarked  
329      1     111361  57.9792   B18        C  
523      1     111361  57.9792   B18        C  
781      0      17474  57.0000   B20        S  
690      0      17474  57.0000   B20        S  
745      1  WE/P 5735  71.0000   B22        S  
..     ...        ...      ...   ...      ...  
618      1     230136  39.0000    F4        S  
251      1     347054  10.4625    G6        S  
10       1    PP 9549  16.7000    G6        S  
205      1     347054  10.4625    G6        S  
394      2    PP 9549  16.7000    G6        S  

[103 rows x 12 columns]

Alguns passageiros não tem cabine registradas: 687

Alguns passageiros tem cabines duplicadas: 103

Alguns passageiros tem mais de uma cabine registrada, provavelmente cabines conexas: 16

Passageiros registrados na mesma cabine tiveram diferentes taxas de sobrevivência, isso pode evidenciar algo relacionado ao posicionamento da pessoa no momento do naufrágio, ou outra característica como idade, dificuldade de locomoção, etc.

### Análise do conjunto de dados de teste

In [767]:
#Clonando o DataFrame teste
testing_data = dataset_test
testing_data

PassengerId  Pclass                                          Name  \
0            892       3                              Kelly, Mr. James   
1            893       3              Wilkes, Mrs. James (Ellen Needs)   
2            894       2                     Myles, Mr. Thomas Francis   
3            895       3                              Wirz, Mr. Albert   
4            896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)   
..           ...     ...                                           ...   
413         1305       3                            Spector, Mr. Woolf   
414         1306       1                  Oliva y Ocana, Dona. Fermina   
415         1307       3                  Saether, Mr. Simon Sivertsen   
416         1308       3                           Ware, Mr. Frederick   
417         1309       3                      Peter, Master. Michael J   

        Sex   Age  SibSp  Parch              Ticket      Fare Cabin Embarked  
0      male  34.5      0      0              330911    7.8292   NaN        Q  
1    female  47.0      1      0              363272    7.0000   NaN        S  
2      male  62.0      0      0              240276    9.6875   NaN        Q  
3      male  27.0      0      0              315154    8.6625   NaN        S  
4    female  22.0      1      1             3101298   12.2875   NaN        S  
..      ...   ...    ...    ...                 ...       ...   ...      ...  
413    male   NaN      0      0           A.5. 3236    8.0500   NaN        S  
414  female  39.0      0      0            PC 17758  108.9000  C105        C  
415    male  38.5      0      0  SOTON/O.Q. 3101262    7.2500   NaN        S  
416    male   NaN      0      0              359309    8.0500   NaN        S  
417    male   NaN      1      1                2668   22.3583   NaN        C  

[418 rows x 11 columns]

In [768]:
# Informa a identificação do passageiro na lista
testing_data['PassengerId'].describe()

count     418.000000
mean     1100.500000
std       120.810458
min       892.000000
25%       996.250000
50%      1100.500000
75%      1204.750000
max      1309.000000
Name: PassengerId, dtype: float64

In [769]:
# Coluna Pclass:
# Informa a classe na qual o passageiro viajava:
testing_data.groupby(['Pclass']).size()

Pclass
1    107
2     93
3    218
dtype: int64

In [770]:
# Conferindo a quantidade.
testing_data['Pclass'].describe()

count    418.000000
mean       2.265550
std        0.841838
min        1.000000
25%        1.000000
50%        3.000000
75%        3.000000
max        3.000000
Name: Pclass, dtype: float64

In [771]:
# Conferindo a quantidade.
testing_data['Name'].describe()

count                  418
unique                 418
top       Kelly, Mr. James
freq                     1
Name: Name, dtype: object

In [772]:
# Coluna sex:
# Informa a quantidade de homens e mulheres:
testing_data['Sex'].value_counts()

male      266
female    152
Name: Sex, dtype: int64

In [773]:
# Conferindo a quantidade.
testing_data['Sex'].describe()

count      418
unique       2
top       male
freq       266
Name: Sex, dtype: object

In [774]:
# Coluna Age:
# Verificar a idade dos passageiros:
testing_data['Age'].describe()
# A quantidade está inferior à 418. Logo temos problemas com quantitativo nessa coluna

count    332.000000
mean      30.272590
std       14.181209
min        0.170000
25%       21.000000
50%       27.000000
75%       39.000000
max       76.000000
Name: Age, dtype: float64

In [775]:
testing_data['Age'].isnull().sum()

86

In [776]:
# Coluna SibSp:
# Informa a quantidade de irmãos e/ou cônjuges à bordo:
testing_data['SibSp'].value_counts()

0    283
1    110
2     14
3      4
4      4
8      2
5      1
Name: SibSp, dtype: int64

In [777]:
# Conferindo a quantidade.
testing_data['SibSp'].describe()

count    418.000000
mean       0.447368
std        0.896760
min        0.000000
25%        0.000000
50%        0.000000
75%        1.000000
max        8.000000
Name: SibSp, dtype: float64

In [778]:
# Coluna Parch:
# Informa a quantidade de pais e/ou filhos à bordo:
testing_data['Parch'].value_counts()

0    324
1     52
2     33
3      3
4      2
9      2
6      1
5      1
Name: Parch, dtype: int64

In [779]:
# Conferindo a quantidade.
testing_data['Parch'].describe()

count    418.000000
mean       0.392344
std        0.981429
min        0.000000
25%        0.000000
50%        0.000000
75%        0.000000
max        9.000000
Name: Parch, dtype: float64

In [780]:
# Coluna Ticket:
# Informa a numeração do Ticket de cada indivíduo:
testing_data['Ticket'].value_counts()

PC 17608    5
CA. 2343    4
113503      4
PC 17483    3
220845      3
           ..
349226      1
2621        1
4133        1
113780      1
2668        1
Name: Ticket, Length: 363, dtype: int64

In [781]:
# Conferindo a quantidade.
testing_data['Ticket'].describe()

count          418
unique         363
top       PC 17608
freq             5
Name: Ticket, dtype: object

In [782]:
# Coluna Fare:
# Informa a tarifa paga:
testing_data['Fare'].describe()

count    417.000000
mean      35.627188
std       55.907576
min        0.000000
25%        7.895800
50%       14.454200
75%       31.500000
max      512.329200
Name: Fare, dtype: float64

Separar para a parte de tratamento de dados:

In [783]:
# Coluna Cabin:
# Informa a cabine que o passageiro ocupava:
testing_data['Cabin'].value_counts()
# Verifica-se que a cabine mais recorrente é a B96

B57 B59 B63 B66    3
B45                2
C89                2
C55 C57            2
A34                2
                  ..
E52                1
D30                1
E31                1
C62 C64            1
C105               1
Name: Cabin, Length: 76, dtype: int64

In [784]:
# Conferindo a quantidade.
testing_data['Cabin'].describe()
# Verifica-se que faltam muitos valores. Temos apenas 91 preenchidos

count                  91
unique                 76
top       B57 B59 B63 B66
freq                    3
Name: Cabin, dtype: object

In [785]:
# Coluna Embarked:
# Informa o porto o qual o passageiro embarcou:
testing_data['Embarked'].value_counts()
# O Porto de Southampton (S) é o mais recorrente.

S    270
C    102
Q     46
Name: Embarked, dtype: int64

In [786]:
# Conferindo a quantidade.
testing_data['Embarked'].describe()

count     418
unique      3
top         S
freq      270
Name: Embarked, dtype: object

Verificação de valores NaN

In [787]:
testing_data.isnull().sum()
# Colunas com valores nulos:
# Age
# Fare
# Cabin

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

Retirando os valores nulos:

In [788]:
#Substituindo os valores NaN pela média:
testing_data['Age'].fillna(int(testing_data['Age'].describe()[1]),inplace=True)
int(testing_data['Age'].describe()[1])

30

In [789]:
#Verificando a existência de algum valor NaN na coluna Age:
testing_data['Age'].isnull().sum()

0

In [790]:
# Coluna Fare:
# Substituindo os valores NaN pela média:
testing_data['Fare'].fillna(int(testing_data['Fare'].describe()[1]),inplace=True)

In [791]:
# Verificando se restam valores nulos:
testing_data['Fare'].isnull().sum()

0

In [792]:
# Coluna Cabin:
testing_data['Cabin'].isnull().sum()
#Verifica-se 327 valores nulos, caracterizando mais da metade.

327

Verificando valores duplicados de algumas colunas: Id, Name e Cabin

In [793]:
# Coluna PassengerId
testing_data[testing_data.duplicated(['PassengerId'],keep=False)]
# Verifica-se que não há valores duplicados

Empty DataFrame
Columns: [PassengerId, Pclass, Name, Sex, Age, SibSp, Parch, Ticket, Fare, Cabin, Embarked]
Index: []

In [794]:
# Coluna Name
testing_data[testing_data.duplicated(['Name'],keep=False)]
# Verifica-se que não há valores duplicados

Empty DataFrame
Columns: [PassengerId, Pclass, Name, Sex, Age, SibSp, Parch, Ticket, Fare, Cabin, Embarked]
Index: []

In [795]:
# Filtra os dados duplicados e não nulos na coluna 'Cabin'
filtered_data_cabin2 = testing_data[testing_data['Cabin'].duplicated(keep=False) & testing_data['Cabin'].notna()]
# Ordena os dados
filtered_data_cabin2 = filtered_data_cabin2.sort_values(by='Cabin')
# Excluindo o indice
filtered_data_cabin2.reset_index(drop=True)
# Exibe os dados
filtered_data_cabin2

PassengerId  Pclass                                               Name  \
293         1185       1                              Dodge, Dr. Washington   
374         1266       1              Dodge, Mrs. Washington (Ruth Vidaver)   
12           904       1      Snyder, Mrs. John Pillsbury (Nelle Stevenson)   
287         1179       1                         Snyder, Mr. John Pillsbury   
24           916       1    Ryerson, Mrs. Arthur Larned (Emily Maria Borie)   
64           956       1                        Ryerson, Master. John Borie   
142         1034       1                         Ryerson, Mr. Arthur Larned   
356         1248       1     Brown, Mrs. John Murray (Caroline Lane Lamson)   
77           969       1  Cornell, Mrs. Robert Clifford (Malvina Helen L...   
177         1069       1                    Stengel, Mr. Charles Emil Henry   
100          992       1  Stengel, Mrs. Charles Emil Henry (Annie May Mo...   
69           961       1                Fortune, Mrs. Mark (Mary McDougald)   
53           945       1                         Fortune, Miss. Ethel Flora   
50           942       1                           Smith, Mr. Lucien Philip   
395         1287       1     Smith, Mrs. Lucien Philip (Mary Eloise Hughes)   
81           973       1                                 Straus, Mr. Isidor   
114         1006       1             Straus, Mrs. Isidor (Rosalie Ida Blun)   
118         1010       1                               Beattie, Mr. Thomson   
270         1162       1                       McCaffry, Mr. Thomas Francis   
411         1303       1    Minahan, Mrs. William Edward (Lillian E Thorpe)   
34           926       1                           Mock, Mr. Philipp Edmund   
218         1110       1       Widener, Mrs. George Dunton (Eleanor Elkins)   
407         1299       1                         Widener, Mr. George Dunton   
272         1164       1      Clark, Mrs. Walter Miller (Virginia McDowell)   
252         1144       1                           Clark, Mr. Walter Miller   
242         1134       1                       Spedden, Mr. Frederic Oakley   
196         1088       1                    Spedden, Master. Robert Douglas   
326         1218       2                       Becker, Miss. Ruth Elizabeth   
178         1070       2   Becker, Mrs. Allen Oliver (Nellie E Baumgardner)   

        Sex   Age  SibSp  Parch    Ticket      Fare            Cabin Embarked  
293    male  53.0      1      1     33638   81.8583              A34        S  
374  female  54.0      1      1     33638   81.8583              A34        S  
12   female  23.0      1      0     21228   82.2667              B45        S  
287    male  24.0      1      0     21228   82.2667              B45        S  
24   female  48.0      1      3  PC 17608  262.3750  B57 B59 B63 B66        C  
64     male  13.0      2      2  PC 17608  262.3750  B57 B59 B63 B66        C  
142    male  61.0      1      3  PC 17608  262.3750  B57 B59 B63 B66        C  
356  female  59.0      2      0     11769   51.4792             C101        S  
77   female  55.0      2      0     11770   25.7000             C101        S  
177    male  54.0      1      0     11778   55.4417             C116        C  
100  female  43.0      1      0     11778   55.4417             C116        C  
69   female  60.0      1      4     19950  263.0000      C23 C25 C27        S  
53   female  28.0      3      2     19950  263.0000      C23 C25 C27        S  
50     male  24.0      1      0     13695   60.0000              C31        S  
395  female  18.0      1      0     13695   60.0000              C31        S  
81     male  67.0      1      0  PC 17483  221.7792          C55 C57        S  
114  female  63.0      1      0  PC 17483  221.7792          C55 C57        S  
118    male  36.0      0      0     13050   75.2417               C6        C  
270    male  46.0      0      0     13050   75.2417               C6        C  
411  female  37.0      1      0   

In [796]:
testing_data['Cabin'].isnull().sum()

327

In [797]:
filtered_data_cabin2.shape

(29, 11)

Alguns passageiros não tem cabine registradas: 327

Alguns passageiros tem cabines duplicadas: 29

Alguns passageiros tem mais de uma cabine registrada, provavelmente cabines conexas: 7

Passageiros registrados na mesma cabine tiveram diferentes taxas de sobrevivência, isso pode evidenciar algo relacionado ao posicionamento da pessoa no momento do naufrágio, ou outra característica como idade, dificuldade de locomoção, etc.

## Pré-processamento, limpeza e tratamento dos dados

### Pré-processamento e limpeza dos dados

In [798]:
testing_data.isnull().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          327
Embarked         0
dtype: int64

In [799]:
training_data.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         0
dtype: int64

Existem valores ausentessomente na coluna Cabin.

Vamos proceder com o tratamento dos dados ausentes

In [800]:
# Substituindo os valores NaN de Cabin por zero:
training_data['Cabin'].fillna(0,inplace=True)
#Verificando a existência de algum valor NaN:
training_data['Cabin'].isnull().sum()

0

In [801]:
# Substituindo os valores NaN de Cabin por zero:
testing_data['Cabin'].fillna(0,inplace=True)
#Verificando a existência de algum valor NaN:
testing_data['Cabin'].isnull().sum()

0

In [802]:
training_data

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female  29.0      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500     0        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250     0        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500     0        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000     0        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500     0        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500     0        Q  

[891 rows x 12 columns]

In [803]:
training_data.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [804]:
testing_data

PassengerId  Pclass                                          Name  \
0            892       3                              Kelly, Mr. James   
1            893       3              Wilkes, Mrs. James (Ellen Needs)   
2            894       2                     Myles, Mr. Thomas Francis   
3            895       3                              Wirz, Mr. Albert   
4            896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)   
..           ...     ...                                           ...   
413         1305       3                            Spector, Mr. Woolf   
414         1306       1                  Oliva y Ocana, Dona. Fermina   
415         1307       3                  Saether, Mr. Simon Sivertsen   
416         1308       3                           Ware, Mr. Frederick   
417         1309       3                      Peter, Master. Michael J   

        Sex   Age  SibSp  Parch              Ticket      Fare Cabin Embarked  
0      male  34.5      0      0              330911    7.8292     0        Q  
1    female  47.0      1      0              363272    7.0000     0        S  
2      male  62.0      0      0              240276    9.6875     0        Q  
3      male  27.0      0      0              315154    8.6625     0        S  
4    female  22.0      1      1             3101298   12.2875     0        S  
..      ...   ...    ...    ...                 ...       ...   ...      ...  
413    male  30.0      0      0           A.5. 3236    8.0500     0        S  
414  female  39.0      0      0            PC 17758  108.9000  C105        C  
415    male  38.5      0      0  SOTON/O.Q. 3101262    7.2500     0        S  
416    male  30.0      0      0              359309    8.0500     0        S  
417    male  30.0      1      1                2668   22.3583     0        C  

[418 rows x 11 columns]

In [805]:
testing_data.isnull().sum()

PassengerId    0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

Confirmamos que não há mais nenhum valor ausentes nos dois datasets

### Tratamento dos dados


Agora iremos para a segunda etapa de modificação das colunas com valores não numéricos. Essa etapa é chamada de "codificação" e visa transformar os valores não numéricos em formatos que possam ser interpretados por algoritmos de análise e modelagem. Isso é essencial para garantir que os dados sejam adequados para análises estatísticas e de aprendizado de máquina, permitindo que os modelos compreendam as informações presentes nas colunas não numéricas. Existem várias técnicas de codificação, como a codificação one-hot e a codificação de rótulos, que podem ser aplicadas dependendo das características dos dados e dos objetivos da análise.

#### Vamos proceder com a codificação dos dados do dataset training_data

In [806]:
# Lista de colunas numéricas
colunas_numericas = training_data.select_dtypes(include=[np.number]).columns.tolist()

# Lista de colunas não numéricas
colunas_nao_numericas = training_data.select_dtypes(exclude=[np.number]).columns.tolist()

print("Colunas Numéricas:")
print(colunas_numericas)

print("\nColunas Não Numéricas:")
print(colunas_nao_numericas)

Colunas Numéricas:
['PassengerId', 'Survived', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare']

Colunas Não Numéricas:
['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked']


A coluna nome não precisa de nenhum tipo de tratamento pois será desconsiderada para a análise do Machine Learning. Vamos prosseguir para as demais colunas.

In [807]:
# Realizando one-hot encoding na coluna "Sex"
one_hot_encoded = pd.get_dummies(training_data['Sex'], prefix='Sex')

# Adicionando as colunas codificadas ao DataFrame original
training_data = pd.concat([training_data, one_hot_encoded], axis=1)

In [808]:
# Codificando a coluna Embarked:
one_hot_code = pd.get_dummies(testing_data['Embarked'], prefix='Embarked')
# Conccatenando ao DataFrame original
training_data = pd.concat([training_data, one_hot_code],axis=1)

training_data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  Sex_female  Sex_male  \
0      0         A/5 21171   7.2500     0        S           0         1   
1      0          PC 17599  71.2833   C85        C           1         0   
2      0  STON/O2. 3101282   7.9250     0        S           1         0   
3      0            113803  53.1000  C123        S           1         0   
4      0            373450   8.0500     0        S           0         1   

   Embarked_C  Embarked_Q  Embarked_S  
0         0.0         1.0         0.0  
1         0.0         0.0         1.0  
2         0.0         1.0         0.0  
3         0.0         0.0         1.0  
4         0.0         0.0         1.0

In [809]:
training_data

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female  29.0      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  Sex_female  Sex_male  \
0        0         A/5 21171   7.2500     0        S           0         1   
1        0          PC 17599  71.2833   C85        C           1         0   
2        0  STON/O2. 3101282   7.9250     0        S           1         0   
3        0            113803  53.1000  C123        S           1         0   
4        0            373450   8.0500     0        S           0         1   
..     ...               ...      ...   ...      ...         ...       ...   
886      0            211536  13.0000     0        S           0         1   
887      0            112053  30.0000   B42        S           1         0   
888      2        W./C. 6607  23.4500     0        S           1         0   
889      0            111369  30.0000  C148        C           0         1   
890      0            370376   7.7500     0        Q           0         1   

     Embarked_C  Embarked_Q  Embarked_S  
0           0.0         1.0         0.0  
1           0.0         0.0         1.0  
2           0.0         1.0         0.0  
3           0.0         0.0         1.0  
4           0.0         0.0         1.0  
..          ...         ...         ...  
886         NaN         NaN         NaN  
887         NaN         NaN         NaN  
888         NaN         NaN         NaN  
889         NaN         NaN         NaN  
890         NaN         NaN         NaN  

[891 rows x 17 columns]

##### Para as colunas "Ticket" e "Cabin" o trabalho será mais árduo, pois teremos que fazer um pré-processamento antes da codificação, devido a grande quantidade de valores diferenciados nessas colunas, veja:

In [810]:
# Verificando os valores únicos em "Ticket" e "Cabin"
print('Valores únicos em Ticket:', len(training_data['Ticket'].value_counts()))
print('Valores únicos em Cabin:', len(training_data['Cabin'].value_counts()))

Valores únicos em Ticket: 681
Valores únicos em Cabin: 148


###### Vamos proceder com a transformação da coluna Ticket

In [811]:
# Criando uma nova coluna "Ticket_value" e outra "Ticket_number"
training_data['Ticket_value'] = training_data['Ticket'].str.split(' ').str[0]
training_data['Ticket_number'] = training_data['Ticket'].str.split(' ').str[1]

# Copiando valores de "Ticket_value" para "Ticket_number" quando estiver com valor NaN
training_data['Ticket_number'].fillna(training_data['Ticket_value'], inplace=True)
for i in range(len(training_data['Ticket_number'])):
  if training_data['Ticket_number'][i].isnumeric() == False:
    training_data['Ticket_number'][i] = 0

# Transformando valores da coluna "Ticket_number" em numéricos
training_data['Ticket_number'] = pd.to_numeric(training_data['Ticket_number'])

# Transformando valores numéricos em NaN na coluna "Ticket_value"
training_data['Ticket_value'] = np.where(pd.to_numeric(training_data['Ticket_value'], errors='coerce').notnull(), np.nan, training_data['Ticket_value'])

# Exibindo as primeiras linhas do DataFrame com a coluna atualizada
training_data

<ipython-input-811-ade3d66b5710>:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  training_data['Ticket_number'][i] = 0


PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female  29.0      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  Sex_female  Sex_male  \
0        0         A/5 21171   7.2500     0        S           0         1   
1        0          PC 17599  71.2833   C85        C           1         0   
2        0  STON/O2. 3101282   7.9250     0        S           1         0   
3        0            113803  53.1000  C123        S           1         0   
4        0            373450   8.0500     0        S           0         1   
..     ...               ...      ...   ...      ...         ...       ...   
886      0            211536  13.0000     0        S           0         1   
887      0            112053  30.0000   B42        S           1         0   
888      2        W./C. 6607  23.4500     0        S           1         0   
889      0            111369  30.0000  C148        C           0         1   
890      0            370376   7.7500     0        Q           0         1   

     Embarked_C  Embarked_Q  Embarked_S Ticket_value  Ticket_number  
0           0.0         1.0         0.0          A/5          21171  
1           0.0         0.0         1.0           PC          17599  
2           0.0         1.0         0.0     STON/O2.        3101282  
3           0.0         0.0         1.0          NaN         113803  
4           0.0         0.0         1.0          NaN         373450  
..          ...         ...         ...          ...            ...  
886         NaN         NaN         NaN          NaN         211536  
887         NaN         NaN         NaN          NaN         112053  
888         NaN         NaN         NaN        W./C.           6607  
889         NaN         NaN         NaN          NaN         111369  
890         NaN         NaN         NaN          NaN         370376  

[891 rows x 19 columns]

In [812]:
# Verificando os valores únicos em "Ticket Value"
training_data['Ticket_value'].value_counts()

PC            60
C.A.          27
STON/O        12
A/5           10
W./C.          9
CA.            8
SOTON/O.Q.     8
A/5.           7
SOTON/OQ       7
STON/O2.       6
CA             6
F.C.C.         5
C              5
SC/PARIS       5
S.O.C.         5
SC/Paris       4
LINE           4
A/4            3
PP             3
A/4.           3
S.O./P.P.      3
SC/AH          3
A.5.           2
A./5.          2
P/PP           2
WE/P           2
SOTON/O2       2
S.C./PARIS     2
S.W./PP        1
F.C.           1
A/S            1
SO/C           1
W/C            1
SC             1
SCO/W          1
SW/PP          1
Fa             1
S.O.P.         1
S.C./A.4.      1
A4.            1
S.P.           1
W.E.P.         1
C.A./SOTON     1
Name: Ticket_value, dtype: int64

In [813]:
# Verificando a quantidade de valores distintos
training_data['Ticket_value'].nunique()

43

In [814]:
# Criando um mapeamento de valores únicos para códigos começando de 1 (dicionário)
unique_values = training_data['Ticket_value'].unique()
value_to_code = {value: code+1 for code, value in enumerate(unique_values)}

# Aplicando o mapeamento para criar a nova coluna codificada
training_data['Ticket_value_encoded'] = training_data['Ticket_value'].map(value_to_code).fillna(0).astype(int)

# Preenchendo os valores nulos por zero:
training_data['Ticket_value'].fillna(0,inplace=True)

# Exibindo as primeiras linhas do DataFrame com a coluna codificada
training_data

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female  29.0      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  Sex_female  Sex_male  \
0        0         A/5 21171   7.2500     0        S           0         1   
1        0          PC 17599  71.2833   C85        C           1         0   
2        0  STON/O2. 3101282   7.9250     0        S           1         0   
3        0            113803  53.1000  C123        S           1         0   
4        0            373450   8.0500     0        S           0         1   
..     ...               ...      ...   ...      ...         ...       ...   
886      0            211536  13.0000     0        S           0         1   
887      0            112053  30.0000   B42        S           1         0   
888      2        W./C. 6607  23.4500     0        S           1         0   
889      0            111369  30.0000  C148        C           0         1   
890      0            370376   7.7500     0        Q           0         1   

     Embarked_C  Embarked_Q  Embarked_S Ticket_value  Ticket_number  \
0           0.0         1.0         0.0          A/5          21171   
1           0.0         0.0         1.0           PC          17599   
2           0.0         1.0         0.0     STON/O2.        3101282   
3           0.0         0.0         1.0            0         113803   
4           0.0         0.0         1.0            0         373450   
..          ...         ...         ...          ...            ...   
886         NaN         NaN         NaN            0         211536   
887         NaN         NaN         NaN            0         112053   
888         NaN         NaN         NaN        W./C.           6607   
889         NaN         NaN         NaN            0         111369   
890         NaN         NaN         NaN            0         370376   

     Ticket_value_encoded  
0                       1  
1                       2  
2                       3  
3                       4  
4                       4  
..                    ...  
886                     4  
887                     4  
888                    16  
889                     4  
890                     4  

[891 rows x 20 columns]

In [815]:
# Concatenando a coluna "Ticket_value_encoded" com a coluna "Ticket_number" em "Ticket_final"
training_data['Ticket_final'] = training_data['Ticket_value_encoded'].astype(str) + training_data['Ticket_number'].astype(str)

# Transformando a coluna "Ticket_final" em valores numéricos
training_data['Ticket_final'] = pd.to_numeric(training_data['Ticket_final'])

# Exibindo as primeiras linhas do DataFrame com a coluna numérica "Ticket_final"
training_data.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare  ... Embarked Sex_female  Sex_male  \
0      0         A/5 21171   7.2500  ...        S          0         1   
1      0          PC 17599  71.2833  ...        C          1         0   
2      0  STON/O2. 3101282   7.9250  ...        S          1         0   

   Embarked_C  Embarked_Q  Embarked_S  Ticket_value Ticket_number  \
0         0.0         1.0         0.0           A/5         21171   
1         0.0         0.0         1.0            PC         17599   
2         0.0         1.0         0.0      STON/O2.       3101282   

   Ticket_value_encoded  Ticket_final  
0                     1        121171  
1                     2        217599  
2                     3      33101282  

[3 rows x 21 columns]

###### Agora vamos transformar a coluna "Cabin" em numérica

In [816]:
training_data['Cabin'].value_counts()

0              687
C23 C25 C27      4
G6               4
B96 B98          4
C22 C26          3
              ... 
E34              1
C7               1
C54              1
E36              1
C148             1
Name: Cabin, Length: 148, dtype: int64

As letras dos códigos das Cabines segundo referência da planta do Titanic do  são: 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'T'

In [817]:
# Dicionário de mapeamento de letras para números
letter_to_number = {'A': 1, 'B': 2, 'C': 3, 'D': 4, 'E': 5, 'F': 6, 'G': 7, 'T': 8}

# Criando uma nova coluna "Cabin_encoded" usando o dicionário de mapeamento
# Função para mapear letras para números
def map_letters_to_numbers(cabin):
    if isinstance(cabin, str):
        new_cabin = ''
        for letter in cabin:
            if letter in letter_to_number:
                new_cabin += str(letter_to_number[letter])
        return int(new_cabin) if new_cabin else None
    else:
        return None

# Aplicando a função à coluna "Cabin"
training_data['Cabin_encoded'] = training_data['Cabin'].apply(map_letters_to_numbers).astype('Int64')

# Obtendo a parte numérica da coluna "Cabin" de 0 a 9
training_data['Cabin_number'] = training_data['Cabin'].str.extractall('(\d+)').groupby(level=0).apply(lambda x: ''.join(x[0]))

# Combinando "Cabin_encoded" e "Cabin_number" em uma nova coluna "Cabin_combined"
training_data['Cabin_combined'] = training_data['Cabin_encoded'].astype(str) + training_data['Cabin_number'].fillna('')

# Transformando a coluna "Cabin_number" em valores numéricos
training_data['Cabin_number'] = pd.to_numeric(training_data['Cabin_number']).astype('Int64')

# Removendo o ponto '.' da coluna "Cabin_combined"
training_data['Cabin_combined'] = training_data['Cabin_combined'].str.replace('.', '', regex=False)

# Substituindo "nan" por 0 na coluna "Cabin_combined"
training_data['Cabin_combined'] = training_data['Cabin_combined'].replace('nan', '0')

# Transformando a coluna "Cabin_combined" em valores numéricos
training_data['Cabin_combined'] = pd.to_numeric(training_data['Cabin_combined'], errors='coerce').astype('Int64')

# Substituindo os valores ausentes nas colunas relacionas a Cabine por 0
training_data['Cabin_combined'].fillna(0, inplace=True)
training_data['Cabin_encoded'].fillna(0,inplace=True)
training_data['Cabin_number'].fillna(0,inplace=True)

# Exibindo as primeiras linhas do DataFrame com a coluna "Cabin_encoded"
training_data.head(30)

PassengerId  Survived  Pclass  \
0             1         0       3   
1             2         1       1   
2             3         1       3   
3             4         1       1   
4             5         0       3   
5             6         0       3   
6             7         0       1   
7             8         0       3   
8             9         1       3   
9            10         1       2   
10           11         1       3   
11           12         1       1   
12           13         0       3   
13           14         0       3   
14           15         0       3   
15           16         1       2   
16           17         0       3   
17           18         1       2   
18           19         0       3   
19           20         1       3   
20           21         0       2   
21           22         1       2   
22           23         1       3   
23           24         1       1   
24           25         0       3   
25           26         1       3   
26           27         0       3   
27           28         0       1   
28           29         1       3   
29           30         0       3   

                                                 Name     Sex   Age  SibSp  \
0                             Braund, Mr. Owen Harris    male  22.0      1   
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                              Heikkinen, Miss. Laina  female  26.0      0   
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                            Allen, Mr. William Henry    male  35.0      0   
5                                    Moran, Mr. James    male  29.0      0   
6                             McCarthy, Mr. Timothy J    male  54.0      0   
7                      Palsson, Master. Gosta Leonard    male   2.0      3   
8   Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                 Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   
10                    Sandstrom, Miss. Marguerite Rut  female   4.0      1   
11                           Bonnell, Miss. Elizabeth  female  58.0      0   
12                     Saundercock, Mr. William Henry    male  20.0      0   
13                        Andersson, Mr. Anders Johan    male  39.0      1   
14               Vestrom, Miss. Hulda Amanda Adolfina  female  14.0      0   
15                   Hewlett, Mrs. (Mary D Kingcome)   female  55.0      0   
16                               Rice, Master. Eugene    male   2.0      4   
17                       Williams, Mr. Charles Eugene    male  29.0      0   
18  Vander Planke, Mrs. Julius (Emelia Maria Vande...  female  31.0      1   
19                            Masselmani, Mrs. Fatima  female  29.0      0   
20                               Fynney, Mr. Joseph J    male  35.0      0   
21                              Beesley, Mr. Lawrence    male  34.0      0   
22                        McGowan, Miss. Anna "Annie"  female  15.0      0   
23                       Sloper, Mr. William Thompson    male  28.0      0   
24                      Palsson, Miss. Torborg Danira  female   8.0      3   
25  Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...  female  38.0      1   
26                            Emir, Mr. Farred Chehab    male  29.0      0   
27                     Fortune, Mr. Charles Alexander    male  19.0      3   
28                      O'Dwyer, Miss. Ellen "Nellie"  female  29.0      0   
29                                Todoroff, Mr. Lalio    male  29.0      0   

    Parch            Ticket      Fare  ... Embarked_C Embarked_Q  Embarked_S  \
0       0         A/5 21171    7.2500  ...        0.0        1.0         0.0   
1       0          PC 17599   71.2833  ...        0.0        0.0         1.0   
2       0  STON/O2. 3101282    7.9250  ...        0.0        1.0         0.0   
3       0            113803   53.1000  ...        0.0        0.0         1.0   
4       0            373450    8.0500

#### Vamos proceder com a codificação dos dados do dataset testing_data

In [818]:
# Lista de colunas numéricas
colunas_numericas_test = testing_data.select_dtypes(include=[np.number]).columns.tolist()

# Lista de colunas não numéricas
colunas_nao_numericas_test = testing_data.select_dtypes(exclude=[np.number]).columns.tolist()

print("Colunas Numéricas:")
print(colunas_numericas_test)

print("\nColunas Não Numéricas:")
print(colunas_nao_numericas_test)

Colunas Numéricas:
['PassengerId', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare']

Colunas Não Numéricas:
['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked']


A coluna nome não precisa de nenhum tipo de tratamento pois será desconsiderada para a análise do Machine Learning. Vamos prosseguir para as demais colunas.

In [819]:
testing_data.shape

(418, 11)

In [820]:
# Realizando one-hot encoding na coluna "Sex"
one_hot_encoded = pd.get_dummies(testing_data['Sex'], prefix='Sex')

# Adicionando as colunas codificadas ao DataFrame original
testing_data = pd.concat([testing_data, one_hot_encoded], axis=1)

In [821]:
testing_data.shape

(418, 13)

In [822]:
one_hot_code = pd.get_dummies(testing_data['Embarked'], prefix='Embarked')

testing_data = pd.concat([testing_data, one_hot_code],axis=1)

testing_data.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  Sex_female  Sex_male  \
0  34.5      0      0   330911   7.8292     0        Q           0         1   
1  47.0      1      0   363272   7.0000     0        S           1         0   
2  62.0      0      0   240276   9.6875     0        Q           0         1   
3  27.0      0      0   315154   8.6625     0        S           0         1   
4  22.0      1      1  3101298  12.2875     0        S           1         0   

   Embarked_C  Embarked_Q  Embarked_S  
0           0           1           0  
1           0           0           1  
2           0           1           0  
3           0           0           1  
4           0           0           1

#####Para as colunas "Ticket" e "Cabin" o trabalho será mais árduo, pois teremos que fazer um pré-processamento antes da codificação, devido a grande quantidade de valores diferenciados nessas colunas, veja:

In [823]:
# Verificando os valores únicos em "Ticket" e "Cabin"
print('Valores únicos em Ticket:', len(testing_data['Ticket'].value_counts()))
print('Valores únicos em Cabin:', len(testing_data['Cabin'].value_counts()))

Valores únicos em Ticket: 363
Valores únicos em Cabin: 77


###### Vamos proceder com a transformação da coluna Ticket

In [824]:
# Criando uma nova coluna "Ticket_value" e outra "Ticket_number"
testing_data['Ticket_value'] = testing_data['Ticket'].str.split(' ').str[0]
testing_data['Ticket_number'] = testing_data['Ticket'].str.split(' ').str[1]

# Copiando valores de "Ticket_value" para "Ticket_number" quando estiver com valor NaN
testing_data['Ticket_number'].fillna(testing_data['Ticket_value'], inplace=True)
for i in range(len(testing_data['Ticket_number'])):
  if testing_data['Ticket_number'][i].isnumeric() == False:
    testing_data['Ticket_number'][i] = 0

# Transformando valores da coluna "Ticket_number" em numéricos
testing_data['Ticket_number'] = pd.to_numeric(testing_data['Ticket_number']).astype('Int64')

# Transformando valores numéricos em NaN na coluna "Ticket_value"
testing_data['Ticket_value'] = np.where(pd.to_numeric(testing_data['Ticket_value'], errors='coerce').notnull(), np.nan, testing_data['Ticket_value'])

# Exibindo as primeiras linhas do DataFrame com a coluna atualizada
testing_data

<ipython-input-824-6160037829a7>:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  testing_data['Ticket_number'][i] = 0


PassengerId  Pclass                                          Name  \
0            892       3                              Kelly, Mr. James   
1            893       3              Wilkes, Mrs. James (Ellen Needs)   
2            894       2                     Myles, Mr. Thomas Francis   
3            895       3                              Wirz, Mr. Albert   
4            896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)   
..           ...     ...                                           ...   
413         1305       3                            Spector, Mr. Woolf   
414         1306       1                  Oliva y Ocana, Dona. Fermina   
415         1307       3                  Saether, Mr. Simon Sivertsen   
416         1308       3                           Ware, Mr. Frederick   
417         1309       3                      Peter, Master. Michael J   

        Sex   Age  SibSp  Parch              Ticket      Fare Cabin Embarked  \
0      male  34.5      0      0              330911    7.8292     0        Q   
1    female  47.0      1      0              363272    7.0000     0        S   
2      male  62.0      0      0              240276    9.6875     0        Q   
3      male  27.0      0      0              315154    8.6625     0        S   
4    female  22.0      1      1             3101298   12.2875     0        S   
..      ...   ...    ...    ...                 ...       ...   ...      ...   
413    male  30.0      0      0           A.5. 3236    8.0500     0        S   
414  female  39.0      0      0            PC 17758  108.9000  C105        C   
415    male  38.5      0      0  SOTON/O.Q. 3101262    7.2500     0        S   
416    male  30.0      0      0              359309    8.0500     0        S   
417    male  30.0      1      1                2668   22.3583     0        C   

     Sex_female  Sex_male  Embarked_C  Embarked_Q  Embarked_S Ticket_value  \
0             0         1           0           1           0          NaN   
1             1         0           0           0           1          NaN   
2             0         1           0           1           0          NaN   
3             0         1           0           0           1          NaN   
4             1         0           0           0           1          NaN   
..          ...       ...         ...         ...         ...          ...   
413           0         1           0           0           1         A.5.   
414           1         0           1           0           0           PC   
415           0         1           0           0           1   SOTON/O.Q.   
416           0         1           0           0           1          NaN   
417           0         1           1           0           0          NaN   

     Ticket_number  
0           330911  
1           363272  
2           240276  
3           315154  
4          3101298  
..             ...  
413           3236  
414          17758  
415        3101262  
416         359309  
417           2668  

[418 rows x 18 columns]

In [825]:
# Verificando os valores únicos em "Ticket Value"
testing_data['Ticket_value'].value_counts()

PC            32
C.A.          19
SOTON/O.Q.     8
SC/PARIS       6
W./C.          5
CA.            4
S.O./P.P.      4
CA             4
F.C.C.         4
A/4            3
C              3
A/5.           3
F.C.           2
A/5            2
S.O.C.         2
STON/O         2
SC/AH          2
LP             1
SC/Paris       1
AQ/4           1
SC             1
A.             1
S.C./PARIS     1
AQ/3.          1
STON/OQ.       1
SOTON/O2       1
SC/A4          1
SOTON/OQ       1
W.E.P.         1
PP             1
A./5.          1
SC/A.3         1
STON/O2.       1
A.5.           1
Name: Ticket_value, dtype: int64

In [826]:
# Verificando a quantidade de valores distintos
testing_data['Ticket_value'].describe()

count     122
unique     34
top        PC
freq       32
Name: Ticket_value, dtype: object

In [827]:
# Criando um mapeamento de valores únicos para códigos começando de 1 (dicionário)
# Foram utilizados os valores únicos da tabela de treinamento:
unique_values = training_data['Ticket_value'].unique()
value_to_code = {value: code+1 for code, value in enumerate(unique_values)}

# Aplicando o mapeamento para criar a nova coluna codificada
testing_data['Ticket_value_encoded'] = testing_data['Ticket_value'].map(value_to_code).fillna(0).astype(int)

# Preenchendo os valores nulos por zero:
testing_data['Ticket_value'].fillna(0,inplace=True)
# Exibindo as primeiras linhas do DataFrame com a coluna codificada
testing_data

PassengerId  Pclass                                          Name  \
0            892       3                              Kelly, Mr. James   
1            893       3              Wilkes, Mrs. James (Ellen Needs)   
2            894       2                     Myles, Mr. Thomas Francis   
3            895       3                              Wirz, Mr. Albert   
4            896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)   
..           ...     ...                                           ...   
413         1305       3                            Spector, Mr. Woolf   
414         1306       1                  Oliva y Ocana, Dona. Fermina   
415         1307       3                  Saether, Mr. Simon Sivertsen   
416         1308       3                           Ware, Mr. Frederick   
417         1309       3                      Peter, Master. Michael J   

        Sex   Age  SibSp  Parch              Ticket      Fare Cabin Embarked  \
0      male  34.5      0      0              330911    7.8292     0        Q   
1    female  47.0      1      0              363272    7.0000     0        S   
2      male  62.0      0      0              240276    9.6875     0        Q   
3      male  27.0      0      0              315154    8.6625     0        S   
4    female  22.0      1      1             3101298   12.2875     0        S   
..      ...   ...    ...    ...                 ...       ...   ...      ...   
413    male  30.0      0      0           A.5. 3236    8.0500     0        S   
414  female  39.0      0      0            PC 17758  108.9000  C105        C   
415    male  38.5      0      0  SOTON/O.Q. 3101262    7.2500     0        S   
416    male  30.0      0      0              359309    8.0500     0        S   
417    male  30.0      1      1                2668   22.3583     0        C   

     Sex_female  Sex_male  Embarked_C  Embarked_Q  Embarked_S Ticket_value  \
0             0         1           0           1           0            0   
1             1         0           0           0           1            0   
2             0         1           0           1           0            0   
3             0         1           0           0           1            0   
4             1         0           0           0           1            0   
..          ...       ...         ...         ...         ...          ...   
413           0         1           0           0           1         A.5.   
414           1         0           1           0           0           PC   
415           0         1           0           0           1   SOTON/O.Q.   
416           0         1           0           0           1            0   
417           0         1           1           0           0            0   

     Ticket_number  Ticket_value_encoded  
0           330911                     0  
1           363272                     0  
2           240276                     0  
3           315154                     0  
4          3101298                     0  
..             ...                   ...  
413           3236                    25  
414          17758                     2  
415        3101262                    22  
416         359309                     0  
417           2668                     0  

[418 rows x 19 columns]

In [828]:
# Concatenando a coluna "Ticket_value_encoded" com a coluna "Ticket_number" em "Ticket_final"
testing_data['Ticket_final'] = testing_data['Ticket_value_encoded'].astype(str) + testing_data['Ticket_number'].astype(str)

# Transformando a coluna "Ticket_final" em valores numéricos
testing_data['Ticket_final'] = pd.to_numeric(testing_data['Ticket_final'])

# Exibindo as primeiras linhas do DataFrame com a coluna numérica "Ticket_final"
testing_data.head(3)

PassengerId  Pclass                              Name     Sex   Age  SibSp  \
0          892       3                  Kelly, Mr. James    male  34.5      0   
1          893       3  Wilkes, Mrs. James (Ellen Needs)  female  47.0      1   
2          894       2         Myles, Mr. Thomas Francis    male  62.0      0   

   Parch  Ticket    Fare Cabin Embarked  Sex_female  Sex_male  Embarked_C  \
0      0  330911  7.8292     0        Q           0         1           0   
1      0  363272  7.0000     0        S           1         0           0   
2      0  240276  9.6875     0        Q           0         1           0   

   Embarked_Q  Embarked_S Ticket_value  Ticket_number  Ticket_value_encoded  \
0           1           0            0         330911                     0   
1           0           1            0         363272                     0   
2           1           0            0         240276                     0   

   Ticket_final  
0        330911  
1        363272  
2        240276

###### Agora vamos transformar a coluna "Cabin" em numérica

In [829]:
testing_data['Cabin'].value_counts()

0                  327
B57 B59 B63 B66      3
C89                  2
C116                 2
C80                  2
                  ... 
E45                  1
E52                  1
B58 B60              1
C62 C64              1
C105                 1
Name: Cabin, Length: 77, dtype: int64

In [830]:
# Dicionário de mapeamento de letras para números
letter_to_number = {'A': 1, 'B': 2, 'C': 3, 'D': 4, 'E': 5, 'F': 6, 'G': 7, 'T': 8}

# Criando uma nova coluna "Cabin_encoded" usando o dicionário de mapeamento
# Função para mapear letras para números
def map_letters_to_numbers(cabin):
    if isinstance(cabin, str):
        new_cabin = ''
        for letter in cabin:
            if letter in letter_to_number:
                new_cabin += str(letter_to_number[letter])
        return int(new_cabin) if new_cabin else None
    else:
        return None

# Aplicando a função à coluna "Cabin"
testing_data['Cabin_encoded'] = testing_data['Cabin'].apply(map_letters_to_numbers).astype('Int64')

# Obtendo a parte numérica da coluna "Cabin" de 0 a 9
testing_data['Cabin_number'] = testing_data['Cabin'].str.extractall('(\d+)').groupby(level=0).apply(lambda x: ''.join(x[0]))

# Combinando "Cabin_encoded" e "Cabin_number" em uma nova coluna "Cabin_combined"
testing_data['Cabin_combined'] = testing_data['Cabin_encoded'].astype(str) + testing_data['Cabin_number'].fillna('')

# Transformando a coluna "Cabin_number" em valores numéricos
testing_data['Cabin_number'] = pd.to_numeric(testing_data['Cabin_number']).astype('Int64')

# Removendo o ponto '.' da coluna "Cabin_combined"
testing_data['Cabin_combined'] = testing_data['Cabin_combined'].str.replace('.', '', regex=False)

# Substituindo "nan" por 0 na coluna "Cabin_combined"
testing_data['Cabin_combined'] = testing_data['Cabin_combined'].replace('nan', '0')

# Transformando a coluna "Cabin_combined" em valores numéricos
training_data['Cabin_combined'] = pd.to_numeric(training_data['Cabin_combined'], errors='coerce').astype('Int64')

# Transformando a coluna "Cabin_combined" em valores numéricos
testing_data['Cabin_combined'] = pd.to_numeric(testing_data['Cabin_combined'], errors='coerce').astype('Int64')

# Substituindo os valores ausentes nas colunas relacionas a Cabine por 0
testing_data['Cabin_combined'].fillna(0, inplace=True)
testing_data['Cabin_encoded'].fillna(0,inplace=True)
testing_data['Cabin_number'].fillna(0,inplace=True)

# Exibindo as primeiras linhas do DataFrame com a coluna "Cabin_encoded"
testing_data.head(30)

PassengerId  Pclass                                               Name  \
0           892       3                                   Kelly, Mr. James   
1           893       3                   Wilkes, Mrs. James (Ellen Needs)   
2           894       2                          Myles, Mr. Thomas Francis   
3           895       3                                   Wirz, Mr. Albert   
4           896       3       Hirvonen, Mrs. Alexander (Helga E Lindqvist)   
5           897       3                         Svensson, Mr. Johan Cervin   
6           898       3                               Connolly, Miss. Kate   
7           899       2                       Caldwell, Mr. Albert Francis   
8           900       3          Abrahim, Mrs. Joseph (Sophie Halaut Easu)   
9           901       3                            Davies, Mr. John Samuel   
10          902       3                                   Ilieff, Mr. Ylio   
11          903       1                         Jones, Mr. Charles Cresson   
12          904       1      Snyder, Mrs. John Pillsbury (Nelle Stevenson)   
13          905       2                               Howard, Mr. Benjamin   
14          906       1  Chaffee, Mrs. Herbert Fuller (Carrie Constance...   
15          907       2      del Carlo, Mrs. Sebastiano (Argenia Genovesi)   
16          908       2                                  Keane, Mr. Daniel   
17          909       3                                  Assaf, Mr. Gerios   
18          910       3                       Ilmakangas, Miss. Ida Livija   
19          911       3              Assaf Khalil, Mrs. Mariana (Miriam")"   
20          912       1                             Rothschild, Mr. Martin   
21          913       3                          Olsen, Master. Artur Karl   
22          914       1               Flegenheim, Mrs. Alfred (Antoinette)   
23          915       1                    Williams, Mr. Richard Norris II   
24          916       1    Ryerson, Mrs. Arthur Larned (Emily Maria Borie)   
25          917       3                            Robins, Mr. Alexander A   
26          918       1                       Ostby, Miss. Helene Ragnhild   
27          919       3                                  Daher, Mr. Shedid   
28          920       1                            Brady, Mr. John Bertram   
29          921       3                                  Samaan, Mr. Elias   

       Sex   Age  SibSp  Parch            Ticket      Fare            Cabin  \
0     male  34.5      0      0            330911    7.8292                0   
1   female  47.0      1      0            363272    7.0000                0   
2     male  62.0      0      0            240276    9.6875                0   
3     male  27.0      0      0            315154    8.6625                0   
4   female  22.0      1      1           3101298   12.2875                0   
5     male  14.0      0      0              7538    9.2250                0   
6   female  30.0      0      0            330972    7.6292                0   
7     male  26.0      1      1            248738   29.0000                0   
8   female  18.0      0      0              2657    7.2292                0   
9     male  21.0      2      0         A/4 48871   24.1500                0   
10    male  30.0      0      0            349220    7.8958                0   
11    male  46.0      0      0               694   26.0000                0   
12  female  23.0      1      0             21228   82.2667              B45   
13    male  63.0      1      0             24065   26.0000                0   
14  female  47.0      1      0       W.E.P. 5734   61.1750              E31   
15  female  24.0      1      0     SC/PARIS 2167   27.7208                0   
16    male  35.0      0      0            233734   12.3500                0   
17    male  21.0      0      0              2692    7.2250                0   
18  female  27.0      1      0  STON/O2. 3101270    7.9250                0   
19  f

### Dataset com limpeza e tratamento finalizado

#### Training_data_cleaned

In [831]:
# Procurando valores nulos em training_data
training_data.isnull().sum()

PassengerId               0
Survived                  0
Pclass                    0
Name                      0
Sex                       0
Age                       0
SibSp                     0
Parch                     0
Ticket                    0
Fare                      0
Cabin                     0
Embarked                  0
Sex_female                0
Sex_male                  0
Embarked_C              473
Embarked_Q              473
Embarked_S              473
Ticket_value              0
Ticket_number             0
Ticket_value_encoded      0
Ticket_final              0
Cabin_encoded             0
Cabin_number              0
Cabin_combined            0
dtype: int64

Vamos agora criar uma cópia desse dataset para manter a integridade dos dados originais, e posteriormente excluir colunas desnecessárias.

In [832]:
# Criando uma cópia do dataframe antes da exclusão de colunas
training_data_cleaned = training_data.copy()

# Lista de colunas numéricas
colunas_numericas = training_data_cleaned.select_dtypes(include=[np.number]).columns.tolist()

# Lista de colunas não numéricas
colunas_nao_numericas = training_data_cleaned.select_dtypes(exclude=[np.number]).columns.tolist()

print("Colunas Numéricas:")
print(colunas_numericas)

print("\nColunas Não Numéricas:")
print(colunas_nao_numericas)

Colunas Numéricas:
['PassengerId', 'Survived', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare', 'Sex_female', 'Sex_male', 'Embarked_C', 'Embarked_Q', 'Embarked_S', 'Ticket_number', 'Ticket_value_encoded', 'Ticket_final', 'Cabin_encoded', 'Cabin_number', 'Cabin_combined']

Colunas Não Numéricas:
['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked', 'Ticket_value']


Podemos então excluir as seguintes colunas: 'Name', 'Sex', 'Ticket', 'Cabin', 'Embarked', 'Ticket_value'

In [833]:
# Lista das colunas a serem excluídas
columns_to_drop = colunas_nao_numericas

# Excluindo as colunas da lista
training_data_cleaned.drop(columns=columns_to_drop, inplace=True)

# Exibindo as primeiras linhas do DataFrame após a exclusão das colunas
training_data_cleaned

PassengerId  Survived  Pclass   Age  SibSp  Parch     Fare  Sex_female  \
0              1         0       3  22.0      1      0   7.2500           0   
1              2         1       1  38.0      1      0  71.2833           1   
2              3         1       3  26.0      0      0   7.9250           1   
3              4         1       1  35.0      1      0  53.1000           1   
4              5         0       3  35.0      0      0   8.0500           0   
..           ...       ...     ...   ...    ...    ...      ...         ...   
886          887         0       2  27.0      0      0  13.0000           0   
887          888         1       1  19.0      0      0  30.0000           1   
888          889         0       3  29.0      1      2  23.4500           1   
889          890         1       1  26.0      0      0  30.0000           0   
890          891         0       3  32.0      0      0   7.7500           0   

     Sex_male  Embarked_C  Embarked_Q  Embarked_S  Ticket_number  \
0           1         0.0         1.0         0.0          21171   
1           0         0.0         0.0         1.0          17599   
2           0         0.0         1.0         0.0        3101282   
3           0         0.0         0.0         1.0         113803   
4           1         0.0         0.0         1.0         373450   
..        ...         ...         ...         ...            ...   
886         1         NaN         NaN         NaN         211536   
887         0         NaN         NaN         NaN         112053   
888         0         NaN         NaN         NaN           6607   
889         1         NaN         NaN         NaN         111369   
890         1         NaN         NaN         NaN         370376   

     Ticket_value_encoded  Ticket_final  Cabin_encoded  Cabin_number  \
0                       1        121171              0             0   
1                       2        217599              3            85   
2                       3      33101282              0             0   
3                       4       4113803              3           123   
4                       4       4373450              0             0   
..                    ...           ...            ...           ...   
886                     4       4211536              0             0   
887                     4       4112053              2            42   
888                    16        166607              0             0   
889                     4       4111369              3           148   
890                     4       4370376              0             0   

     Cabin_combined  
0                 0  
1               385  
2                 0  
3              3123  
4                 0  
..              ...  
886               0  
887             242  
888               0  
889            3148  
890               0  

[891 rows x 18 columns]

In [834]:
# Lista de colunas numéricas
colunas_numericas = training_data_cleaned.select_dtypes(include=[np.number]).columns.tolist()

# Lista de colunas não numéricas
colunas_nao_numericas = training_data_cleaned.select_dtypes(exclude=[np.number]).columns.tolist()

print("Colunas Numéricas:")
print(colunas_numericas)

print("\nColunas Não Numéricas:")
print(colunas_nao_numericas)

Colunas Numéricas:
['PassengerId', 'Survived', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare', 'Sex_female', 'Sex_male', 'Embarked_C', 'Embarked_Q', 'Embarked_S', 'Ticket_number', 'Ticket_value_encoded', 'Ticket_final', 'Cabin_encoded', 'Cabin_number', 'Cabin_combined']

Colunas Não Numéricas:
[]


In [835]:
# Checando o tipo de dados de cada coluna em training_data_cleaned
training_data_cleaned.dtypes

PassengerId               int64
Survived                  int64
Pclass                    int64
Age                     float64
SibSp                     int64
Parch                     int64
Fare                    float64
Sex_female                uint8
Sex_male                  uint8
Embarked_C              float64
Embarked_Q              float64
Embarked_S              float64
Ticket_number             int64
Ticket_value_encoded      int64
Ticket_final              int64
Cabin_encoded             Int64
Cabin_number              Int64
Cabin_combined            Int64
dtype: object

Ok, agora todas as colunas são numéricas e podem ser utilizadas adequadamente para o aprendizado de máquina.

#### Testing_data_cleaned

In [836]:
# Procurando valores nulos em testing_data
testing_data.isnull().sum()

PassengerId             0
Pclass                  0
Name                    0
Sex                     0
Age                     0
SibSp                   0
Parch                   0
Ticket                  0
Fare                    0
Cabin                   0
Embarked                0
Sex_female              0
Sex_male                0
Embarked_C              0
Embarked_Q              0
Embarked_S              0
Ticket_value            0
Ticket_number           0
Ticket_value_encoded    0
Ticket_final            0
Cabin_encoded           0
Cabin_number            0
Cabin_combined          0
dtype: int64

Vamos agora criar uma cópia desse dataset para manter a integridade dos dados originais, e posteriormente excluir colunas desnecessárias.

In [837]:
# Criando uma cópia do dataframe antes da exclusão de colunas
testing_data_cleaned = testing_data.copy()

# Lista de colunas numéricas
colunas_numericas = testing_data_cleaned.select_dtypes(include=[np.number]).columns.tolist()

# Lista de colunas não numéricas
colunas_nao_numericas = testing_data_cleaned.select_dtypes(exclude=[np.number]).columns.tolist()

print("Colunas Numéricas:")
print(colunas_numericas)

print("\nColunas Não Numéricas:")
print(colunas_nao_numericas)

Colunas Numéricas:
['PassengerId', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare', 'Sex_female', 'Sex_male', 'Embarked_C', 'Embarked_Q', 'Embarked_S', 'Ticket_number', 'Ticket_value_encoded', 'Ticket_final', 'Cabin_encoded', 'Cabin_number', 'Cabin_combined']

Colunas Não Numéricas:
['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked', 'Ticket_value']


Podemos então excluir as seguintes colunas: 'Name', 'Sex', 'Ticket', 'Cabin', 'Embarked', 'Ticket_value'

In [838]:
# Lista das colunas a serem excluídas
columns_to_drop = colunas_nao_numericas

# Excluindo as colunas da lista
testing_data_cleaned.drop(columns=columns_to_drop, inplace=True)

# Exibindo as primeiras linhas do DataFrame após a exclusão das colunas
testing_data_cleaned

PassengerId  Pclass   Age  SibSp  Parch      Fare  Sex_female  Sex_male  \
0            892       3  34.5      0      0    7.8292           0         1   
1            893       3  47.0      1      0    7.0000           1         0   
2            894       2  62.0      0      0    9.6875           0         1   
3            895       3  27.0      0      0    8.6625           0         1   
4            896       3  22.0      1      1   12.2875           1         0   
..           ...     ...   ...    ...    ...       ...         ...       ...   
413         1305       3  30.0      0      0    8.0500           0         1   
414         1306       1  39.0      0      0  108.9000           1         0   
415         1307       3  38.5      0      0    7.2500           0         1   
416         1308       3  30.0      0      0    8.0500           0         1   
417         1309       3  30.0      1      1   22.3583           0         1   

     Embarked_C  Embarked_Q  Embarked_S  Ticket_number  Ticket_value_encoded  \
0             0           1           0         330911                     0   
1             0           0           1         363272                     0   
2             0           1           0         240276                     0   
3             0           0           1         315154                     0   
4             0           0           1        3101298                     0   
..          ...         ...         ...            ...                   ...   
413           0           0           1           3236                    25   
414           1           0           0          17758                     2   
415           0           0           1        3101262                    22   
416           0           0           1         359309                     0   
417           1           0           0           2668                     0   

     Ticket_final  Cabin_encoded  Cabin_number  Cabin_combined  
0          330911              0             0               0  
1          363272              0             0               0  
2          240276              0             0               0  
3          315154              0             0               0  
4         3101298              0             0               0  
..            ...            ...           ...             ...  
413        253236              0             0               0  
414        217758              3           105            3105  
415     223101262              0             0               0  
416        359309              0             0               0  
417          2668              0             0               0  

[418 rows x 17 columns]

In [839]:
# Lista de colunas numéricas
colunas_numericas = testing_data_cleaned.select_dtypes(include=[np.number]).columns.tolist()

# Lista de colunas não numéricas
colunas_nao_numericas = testing_data_cleaned.select_dtypes(exclude=[np.number]).columns.tolist()

print("Colunas Numéricas:")
print(colunas_numericas)

print("\nColunas Não Numéricas:")
print(colunas_nao_numericas)

Colunas Numéricas:
['PassengerId', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare', 'Sex_female', 'Sex_male', 'Embarked_C', 'Embarked_Q', 'Embarked_S', 'Ticket_number', 'Ticket_value_encoded', 'Ticket_final', 'Cabin_encoded', 'Cabin_number', 'Cabin_combined']

Colunas Não Numéricas:
[]


In [840]:
# Checando o tipo de dados de cada coluna em testing_data_cleaned
testing_data_cleaned.dtypes

PassengerId               int64
Pclass                    int64
Age                     float64
SibSp                     int64
Parch                     int64
Fare                    float64
Sex_female                uint8
Sex_male                  uint8
Embarked_C                uint8
Embarked_Q                uint8
Embarked_S                uint8
Ticket_number             Int64
Ticket_value_encoded      int64
Ticket_final              int64
Cabin_encoded             Int64
Cabin_number              Int64
Cabin_combined            Int64
dtype: object

Ok, agora todas as colunas são numéricas e podem ser utilizadas adequadamente para o aprendizado de máquina.

### Salvando os dataframes limpos em arquivo .csv

In [844]:
# Cehcando se os dataframes testing_data_cleaned e training_data_cleaned tem o mesmo shape
print('testing_data_cleaned.shape:', testing_data_cleaned.shape)
print('training_data_cleaned.shape:', training_data_cleaned.shape)

testing_data_cleaned.shape: (418, 17)
training_data_cleaned.shape: (891, 18)


Ok, tudo certo, o training_data_cleaned tem 891 linhas e 18 colunas, uma coluna a mais ('Survived') que o testing_data_cleaned, que possui 418 linhas e 17 colunas.

In [845]:
# Salvando training_data_cleaned em um arquivo .csv
training_data_cleaned.to_csv('training_data_cleaned.csv', index=False)

# Salvando testing_data_cleaned em um arquivo .csv
testing_data_cleaned.to_csv('testing_data_cleaned.csv', index=False)

# O que falta?

-Normalizar os dados não compensa muito nesse caso, pois o enviesamento é o ideal para a tomada de decisão das árvores

-Mais alguma coisa para tratar?

-Olhar o trello

-Olhar a documentação

-Revisar todas as células e códigos

-Prazo da meta desse sprint: 31/08/2023